### ISSUE TITLE
Outputs stay on/off randomly

### ISSUE THREAD

**Issue by LuckyLukeCH** [erminas/noderedrevpinodes-server#11]
Hello,

We started with RevPi with NodeRED in autumn 2021 and had different problems.
Some of them, the memory leak and the input-delay seem to be solved.

Now we wanted to build another system and found, that the outputs on DIO randomly don't behave correct, which means, they don't represent the state of the 'revpi-output' node. The state of the node changes correct according to our process, but the relay sometimes stay on, until the next pulse appears on the output-node.

The behavior is random and we couldn't see it on the older version
node-red-contrib-revpi-nodes@1.0.7-2
and
noderedrevpinodes-server/ bugfix/memleak-buster

Our configuration is Buster and Up-to-date:
22 Apr 09:28:47 - [info] Node-RED version: v2.2.2
22 Apr 09:28:47 - [info] Node.js  version: v12.22.12
22 Apr 09:28:47 - [info] Linux 4.19.95-rt38-v7 arm LE
node-red-contrib-revpi-nodes 1.0.9
noderedrevpinodes-server 1.0.4

On the photo you can see, that the node says O_11 is 0 but the relay 11 stays on:

![IMG_7287](https://user-images.githubusercontent.com/20842834/164646326-6408df44-e30c-4291-bc95-ef7c04c077f5.jpg)

This is our fourth system with RevPi and on every system we had multiple problems:
- Memory Leak
- Digital-Inputs not reading
- Switch Summertime/Wintertime always breaks the MQTT-Connections without reconnection
- This problem
We would like to hear from Kunbus, if they plan to bring the RevPi to a Off-the-shelf working system.

Thank you and regards
Lukas Gaam

**Comment by LuckyLukeCH** [comment]
Hello,

Downgraded to:
- NodeRED 1.3.2
- node-red-contrib-revpi-nodes@1.0.7-2
- nbuchwitz/noderedrevpinodes-server/ bugfix/memleak-buster

Unfortunately must confirm, that the problem stays the same. Attached the photo after relay 8 should switch off!
Seems, that not all of the 200ms pulses get transfered!

![IMG_7288](https://user-images.githubusercontent.com/20842834/164677891-1b1fae2a-33fb-4c53-a685-2d65430563f1.jpg)

**Comment by LuckyLukeCH** [comment]
Hello,

Logged the messages in the noderedrevpinodes-server after line 287:
  ```
  @asyncio.coroutine
    def publish_messages_to_client(self, client, path):
        while client.message_queue:
            message = client.message_queue.pop(0)
            **logging.info(str(client.id) + "," + json.dumps(message))**
            yield from client.websocket.send(message)
```

```
2022-04-22 12:05:09,950 root        : INFO     ae38a4bd-1d70-4af6-a73e-ae32a0294c4f,"output#[\"O_9\",1];{}"
2022-04-22 12:05:09,951 root        : INFO     ae38a4bd-1d70-4af6-a73e-ae32a0294c4f,"output#[\"O_9\",0];{}"
```
The relay 9 stayed on after the last messsage.
So it seems, that the connection between NodeRED and the noderedrevpinodes-server ist working and the problem is after.

Later was the following message, but don't know if it is connected:
```
/usr/lib/python3/dist-packages/revpimodio2/modio.py:1083: RuntimeWarning: can not execute all event functions in one cycle - optimize your event functions or rise .cycletime
  RuntimeWarning
```

**Comment by LuckyLukeCH** [comment]
Hello Nicolai,

Thank you for the response.
The default length is 200ms, but we tried 100ms and 300ms with the same result. Random behavior with any pulse length.

Regards
Lukas Gaam

**Comment by nbuchwitz** [comment]
Hi Lukas,

thanks for the feedback. This week is quite busy, but I've blocked some time next monday to test your setup. Boris and I will keep you updated.

Nicolai

**Comment by LuckyLukeCH** [comment]
Hello Nicolaj,

Thank you. Since we are in a hurry to deliver the system to the customer next week, so we would need a solution by the mid of the week.

Thank you and regards
Lukas

**Comment by nbuchwitz** [comment]
Hi Lukas,

I asked the erminas to have a look at your report, since they are developing the nodered integration.

They will have a look and get back to you asap.

Nicolai

**Comment by dfilsinger-erminas** [comment]
Hello Lukas, 
we will have a look at the issue next week. I have an idea how to solve it. But I can't promise you that we'll be able to fix it by Wednesday.

Regards
Dennis

**Comment by dfilsinger-erminas** [comment]
Hi Lukas, 
we have looked at the problem and come to the conclusion that there is a timing problem between nodered, the websockets and the cycle time of the process image. We will record the bug to fix it with the next version of the server.
For now, we have a workaround in [this branch](https://github.com/erminas/noderedrevpinodes-server/tree/workaround_outputs_switch_with_short_pulses) that will reduce the error rate from 2% to less than 0.2%. 

I hope that helps you for the moment.
Regards
Dennis

**Comment by crismancich** [comment]
That sounds good. Lukas can you test the Workaround? Thank you Dennis.

**Comment by LuckyLukeCH** [comment]
Hi Dennis, hi Boris,

Thank you for the information and the temporary fix.
We tested the new version even with shorter pulses and until now had no/zero false switches. This is good news.

What will be the plans for the new release of the server? We are not so confident to install beta versions at the customers site and problably we can wait for it?

Thank you for your response about your schedules for the new version.
Regards Lukas

**Comment by dfilsinger-erminas** [comment]
Hi Lukas, 

we don't have a schedule for upcoming releases. 
Looking at the release history so far and the planned fixes, I think the next release won't come for a few months. 

Regards 
Dennis

**Comment by LuckyLukeCH** [comment]
Hello Dennis, hello Boris 

After internal tests we installed the version 1.0.4.+ at the customer site and it was a nightmare!
Again random switching and the result of it is really bad in our special application!

Then we tried the version 1.0.5. with the following result in revpi-server.log
`2022-11-02 10:42:24,757 root        : INFO     New client connected and was given id 9441bc42-1e2b-4145-96bc-1f6004b22e96
2022-11-02 10:42:46,816 websockets.server: ERROR    Error in connection handler
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/websockets/server.py", line 169, in handler
    yield from self.ws_handler(self, path)
  File "revpi-server.py", line 457, in handle_clients
    await t
  File "revpi-server.py", line 333, in get_client_requests
    io_names = args[4]
IndexError: list index out of range
`
We can't believe, that after such a long time there is still no working version for this!

Regards
Lukas Gaam

**Comment by hbunjes** [comment]
Hi @LuckyLukeCH,
The version 1.0.5 of the server component requires the RevPi Nodes version 1.1.0 (see https://github.com/erminas/node-red-contrib-revpi-nodes/releases).

The fix was released on Sep 19 as a pre-release. Currently this is in testing at Kunbus before we can make it an official release. This fix has a breaking change with the server/nodes version and, therefore, we can only release the RevPi Nodes version as soon as the server version gets released in the Kunbus packages. 

We hope that testing is finished soon so that the fix gets released officially.

Best,
Hilmar

**Comment by nbuchwitz** [comment]
@hbunjes The error @LuckyLukeCH reported from the server log is independent from the version conflict (index out of range). Looks like there is something broken with the error handling...

**Comment by LuckyLukeCH** [comment]
Hello @nbuchwitz, hello @hbunjes, hello @crismancich 

Thank you for the quick response. We didn't test it with the 1.1.0 nodes, so this is a possible cause.
At the moment we downgraded the system to 1.0.3-1 which was the most stable version concerning the output switching and the memory leakeage. The reading of the inputs is broken in this version, but they are not important in this application.

We should install another two systems but stopped everything until we have a stable version!
Please invest the time to test inputs and outputs seriously for a working version, thank you.

Regards
Lukas Gaam

**Comment by hbunjes** [comment]
> @hbunjes The error @LuckyLukeCH reported from the server log is independent from the version conflict (index out of range). Looks like there is something broken with the error handling...

This is the error caused by the version conflict we have there. The new client sends an additional parameter during login and this parameter could not be accessed from the server which is the index out of range.

Best
Hilmar

**Comment by LuckyLukeCH** [comment]
Hello @hbunjes @crismancich 
Thank you for the information.
We still have the problem with random outputs staying at 1. Even a resend of 0 in NodeRED doesn't help; we need to resend 1 and 0 again, that the correct value is transfered to the output pins!!

We are very unhappy with the RevPi internal communication thru noderedrevpinodes-server!
Could you please provide a working version, which corresponds with the hardware correctly?

If we will not have a working version within the next days, we need to exchange the hardware at the customer site with huge costs! We will not pay for it alone...

Regards 
Lukas Gaam

**Comment by LuckyLukeCH** [comment]
Hello @hbunjes @crismancich

The nodes 1.1.0 are not working in our application, since we are on older NodeRED. Please provide a NodeRED-Node for NodeRED 1.x

Thank you and regards
Lukas Gaam

**Comment by hbunjes** [comment]
Hello,
currently it is not planned to backport this change to an old NodeRED version (current versions are 2.x and 3.x). 

You could try to adjust the node to run with 1.x but we cannot give support for it.

Just for interest: Is there any reason to not switch to NodeRED 2 or 3?

Best
Hilmar

**Comment by hbunjes** [comment]
Fix is in Version 1.0.5 (client version 1.10) pre-released on Sep 19, 2022 included.

Currently waiting for final release by Kunbus.
